ansible_host_key_checking: False

build_dir: "{{ playbook_dir }}/build"

vyos_iso_url: https://s3-us.vyos.io/rolling/current/vyos-rolling-latest.iso
vyos_iso_local: "{{ iso_local | default(build_dir + '/vyos.iso') }}"

vyos_cd_root: "{{ build_dir }}/cdrom"
vyos_cd_squash_root: "{{ build_dir }}/cdsquash"
vyos_squashfs_image: "{{ vyos_cd_root }}/live/filesystem.squashfs"
vyos_write_root: "{{ build_dir }}/wroot"
vyos_read_root: "{{ build_dir }}/squashfs"
vyos_install_root: "{{ build_dir }}/inst_root"

vyos_disk_size: "{{ disk_size | default(10) }}"
vyos_parttable_type: "{{ parttable_type | default('hybrid') }}"
vyos_root_fstype: ext4

vyos_target_drive: ""
vyos_raw_img: "{{ build_dir }}/vyos_raw_image.img"
grub_console: "kvm"
grub_timeout: "5"

enable_dhcp: False
enable_ssh: False

release: False

# https://github.com/hashicorp/vagrant/blob/main/keys/vagrant.pub
vagrant_insecure_key: "AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ=="
