ansible_host_key_checking: False

build_dir: "{{ playbook_dir }}/build"

vyos_iso_url: https://s3-us.vyos.io/rolling/current/vyos-rolling-latest.iso
vyos_iso_local: "{{ iso_local | default(build_dir + '/vyos.iso') }}"

vyos_cd_root: "{{ build_dir }}/cdrom"
vyos_cd_squash_root: "{{ build_dir }}/cdsquash"
vyos_squashfs_image: "{{ vyos_cd_root }}/live/filesystem.squashfs"
vyos_write_root: "{{ build_dir }}/wroot"
vyos_read_root: "{{ build_dir }}/squashfs"
vyos_install_root: "{{ build_dir }}/inst_root"

vyos_disk_size: "{{ disk_size | default(10) }}"
vyos_parttable_type: "{{ parttable_type | default('hybrid') }}"
vyos_root_fstype: ext4

vyos_target_drive: ""
vyos_raw_img: "{{ build_dir }}/vyos_raw_image.img"
grub_console: "kvm"

enable_dhcp: False
enable_ssh: False

release: False
