- name: Create build directory if it does not exist
  become: no
  file:
    path: "{{ build_dir }}"
    state: directory
    mode: '0755'

- name: Download VyOS ISO release
  get_url:
    url: "{{ vyos_iso_url }}"
    dest: "{{ vyos_iso_local }}"
    force: no
