- name: Check Vagrant Cloud login
  become: no
  command: "vagrant cloud auth login --check"

- name: Set box version
  set_fact:
    box_version: "{{ vyos_version.split('-')[2][0:8] }}.{{ vyos_version.split('-')[2][8:10] }}.{{ vyos_version.split('-')[2][10:12] }}"

- name: Publish the Vagrant box
  become: no
  command: "vagrant cloud publish {{ vyos_vagrant_box_name }} {{ box_version }} {{ vagrant_provider }} {{ vyos_output_img }} --version-description \"VyOS {{ vyos_version }}\" --release --force"
