name: Release VyOS current LXD VM images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  lxd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: actions
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'poetry'
      - run: poetry install
      - run: |
          poetry run ansible-playbook lxd-vm.yml
      - uses: actions/upload-artifact@v2
        with:
          name: images
          path: build/*.tar.xz

  upload:
    needs: lxd
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: images

      - run: aws configure set default.s3.max_concurrent_requests 3
  
      - name: upload file
        run: aws --endpoint-url "${ENDPOINT_URL}" s3 sync . s3://${BUCKET_NAME}/rolling/current --exclude "*" --include="*.tar.xz" --delete
        env:
          ENDPOINT_URL: ${{ secrets.ENDPOINT_URL }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: auto # avoid botocore.awsrequest.AWSRequest error
