name: Release VyOS current VM images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  qemu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cloud_init: ['true', 'false']
        grub_console: ['kvm', 'serial']
    steps:
      - uses: actions/checkout@v3
        with:
          ref: actions
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'poetry'
      - run: |
          pip3 install poetry
          poetry install
      - run: |
          poetry run ansible-playbook qemu.yml -e cloud_init=${{ matrix.cloud_init}} -e grub_console=${{ matrix.grub_console }}
      - name: create latest files
        run: |
          for i in `ls *.qcow2`; do
            latest=$(echo $i | sed 's/[0-9]\{12\}/latest/')
            echo "copy $i to $latest"
            cp -p $i $latest
          done
        working-directory: ./build
      - uses: actions/upload-artifact@v2
        with:
          name: images
          path: build/*.qcow2

  upload:
    needs: qemu
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: images

      - run: aws configure set default.s3.max_concurrent_requests 3
  
      - name: upload file
        run: aws --endpoint-url "${ENDPOINT_URL}" s3 sync . s3://${BUCKET_NAME}/rolling/current --exclude "*" --include="*.qcow2" --delete
        env:
          ENDPOINT_URL: ${{ secrets.ENDPOINT_URL }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: auto # avoid botocore.awsrequest.AWSRequest error
