name: Release VyOS current VM images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  qemu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cloud_init: ['true', 'false']
    steps:
      - uses: actions/checkout@v2
        with:
          ref: actions
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: |
          pip3 install poetry
          poetry install
      - run: |
          poetry run ansible-playbook qemu.yml -e cloud_init=${{ matrix.cloud_init}}
      - uses: actions/upload-artifact@v2
        with:
          name: qcow2
          path: build/*.qcow2

  upload:
    needs: qemu
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: qcow2
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
  
      - id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: '.'
          destination: "${{ secrets.BUCKET_NAME }}/images/rolling/current"
          glob: '*.qcow2'
